---
- name: Conf dirs
  file:
    dest: "{{ user_home }}/.config/{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - nvim
    - alacritty

- name: Link dots
  file:
    state: link
    force: yes
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ user_home }}/.{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - zshrc
    - bashrc
    - bash_aliases
    - exports.common
    - vimrc
    - screenrc
    - tmux.conf
    - gitconfig

- name: Link config others
  file:
    state: link
    force: yes
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ user_home }}/.config/{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - starship.toml

- name: Link nvim
  file:
    state: link
    src: "{{ user_home }}/.vimrc"
    dest: "{{ user_home }}/.config/nvim/init.vim"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Link alacritty
  file:
    state: link
    force: yes
    src: "{{ role_path }}/files/alacritty.yml"
    dest: "{{ user_home }}/.config/alacritty/alacritty.yml"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Src dir
  file:
    path: "{{ user_home }}/src"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: vim tmp
  file:
    path: "{{ user_home }}/.vim-tmp"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

# Replicate Plug setup for nvim
# https://github.com/junegunn/vim-plug
#
# curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
#   https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
- name: nvim autoload dir
  file:
    path: "{{ user_home }}/.local/share/nvim/site/autoload"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: nvim plug dl
  get_url:
    url: 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    dest: "{{ user_home }}/.local/share/nvim/site/autoload/plug.vim"
    mode: "0755"
