---
#mkinitcpio_hooks_list: resume
- hosts: tennislframe
  vars:
    hostname_init: tennislframe
    arch_common_swap_hibernate: no
    xresources_file: Xresources.larger
  roles:
    - arch-common
    - dots
    - arch-i3-desktop
    - arch-laptop
