autoload -Uz compinit promptinit edit-command-line select-word-style
select-word-style bash
compinit
promptinit
setopt interactivecomments

bindkey -e

# ctrlx ctrle for editing lines
zle -N edit-command-line
bindkey '^xe' edit-command-line
bindkey '^x^e' edit-command-line

# private stuff, no SCM
[ -f $HOME/.exports ] && source $HOME/.exports

# public common stuff between shells, tracked in SCM
[ -f $HOME/.exports.common ] && source $HOME/.exports.common

function refresh_ssh_autocomplete () {
    host_list=($(grep -r 'Host ' ~/.ssh/ | awk '{s = s $2 " "} END {print s}'))
    zstyle ':completion:*:(ssh|scp|sftp):*' hosts $host_list
}
refresh_ssh_autocomplete

hash starship 1>/dev/null 2>&1 && eval "$(starship init zsh)"
