---
# run docker setup by default
arch_common_docker: 1

# arch_common_swap_hibernate
arch_common_swap_hibernate: no

# default hooks from install
# HOOKS=(base udev autodetect modconf block filesystems keyboard fsck)
mkinitcpio_hooks_list: default

mkinitcpio_hooks_lists:
  default:
    - base
    - udev
    - autodetect
    - modconf
    - block
    - filesystems
    - keyboard
    - fsck

  resume:
    - base
    - udev
    - autodetect
    - modconf
    - block
    - filesystems
    - keyboard
    - resume
    - fsck
