---
- name: Pkgs
  become: yes
  pacman:
    name:
      - tlp
      - xorg-xbacklight
      - brightnessctl
    state: present

- name: tlp
  become: yes
  systemd:
    name: tlp
    enabled: yes
    state: started

- name: touchpad xorg
  become: yes
  file:
    state: link
    src: "{{ role_path }}/files/30-touchpad.conf"
    path: '/etc/X11/xorg.conf.d/30-touchpad.conf'
