---
- name: Pkgs
  become: yes
  pacman:
    name:
      - xorg-xbacklight
      - brightnessctl
    state: present

- name: touchpad xorg
  become: yes
  file:
    state: link
    src: "{{ role_path }}/files/30-touchpad.conf"
    path: '/etc/X11/xorg.conf.d/30-touchpad.conf'

- import_tasks: wifi-radios.yml
  when: "use_sleep_wifi_radios|bool"
