---
- name: Pkgs
  become: yes
  pacman:
    name:
      - tlp
      - xorg-xbacklight
      - brightnessctl
    state: present

- name: tlp
  become: yes
  systemd:
    name: tlp
    enabled: yes
    state: started
