#!/bin/sh

if [ "$1" == "pre" ]; then
	logger "$0 - radios pre"
	rfkill block all
	sleep 1
	modprobe -r $wifi
fi

if [ "$1" == "post" ]; then
	logger "$0 - radios post"
	modprobe $wifi
	sleep 1
	rfkill unblock all
fi
