---
- name: Pkgs
  become: yes
  pacman:
    name:
      - i3-wm
      - sx
      - xorg-xev
      - xorg-xinit
      - xorg-xinput
      - xprintidle
      - xss-lock
      - xclip
      - i3lock
      - i3status
      - i3blocks
      - sxiv
      - bluez
      - bluez-utils
      - pipewire
      - pipewire-pulse
      - pipewire-alsa
      - pavucontrol
      - pasystray
      - alacritty
      - arandr
      - dhclient
      - wireless_tools
      - networkmanager
      - network-manager-applet
      - networkmanager-openvpn
      - networkmanager-vpnc
      - ttf-dejavu
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - ttf-jetbrains-mono
      - ttf-nerd-fonts-symbols-mono
      - nitrogen
      - libmicrodns
      - vlc
      - thunar
      - gvfs
      - gvfs-smb
      - sshfs
      - chromium
      - dunst
      - tlp
      - z
      - blueman
      - lxappearance
      - arc-gtk-theme
      - papirus-icon-theme
      - docker
      - keychain
      - android-udev
      - archlinux-wallpaper
      - redshift
      - flameshot
      - ntfs-3g
      - udiskie
      - udisks2
      - discord
      - transmission-gtk
      - code
      - linux-headers
      - linux-lts-headers
      - virtualbox
      - virtualbox-host-dkms
      - gimp
      - rofi
      - rofimoji
      - xdotool
      - ttf-roboto
      - ttf-roboto-mono
      - mpv
      - hexchat
      - syncthing
      - keepassxc
      - ristretto
    state: present

- name: emptty dir dirs
  become: yes
  file:
    state: directory
    dest: "/etc/emptty"

- name: emptty conf
  become: yes
  file:
    state: link
    force: yes
    src: "{{ role_path }}/files/empttyconf"
    dest: "/etc/emptty/conf"


##############################
### Services
##############################
- name: docker
  become: yes
  systemd:
    name: docker
    enabled: yes
    state: started

- name: docker sytemd
  become: yes
  systemd:
    name: docker
    enabled: yes
    state: started


##############################
### hosts/ssh config
##############################
- set_fact:
    custom_etc_hosts_content: "{{ lookup('template', '{{ role_path }}/templates/custom-etc-hosts-block.j2') }}"

- name: etc hosts
  become: yes
  blockinfile:
    path: "/etc/hosts"
    content: '{{ custom_etc_hosts_content }}'
    marker: '# {mark} custom hosts: ansible managed block'

- name: ssh config custom
  blockinfile:
    path: "{{ user_home }}/.ssh/config"
    create: yes
    owner: "{{ user }}"
    group: "{{ user }}"
    marker: '# {mark} ssh config custom: ansible managed block'
    insertbefore: 'BOF'
    block: |
      Host tennisp1
          User collin
          StrictHostKeyChecking no
          UserKnownHostsFile=/dev/null

      Host droplet2
          HostName 162.243.19.32
          User collin

      Host pixeltermux
          User u0_a523
          Port 8022

##############################
### syncthing
##############################
- name: syncthing service
  become: yes
  systemd:
    name: "syncthing@{{ user }}.service"
    daemon_reload: no
    state: started
    enabled: yes

##############################
### bluetooth
##############################
- name: bluetooth
  become: yes
  systemd:
    name: bluetooth
    enabled: yes
    state: started

- name: bluetooth auto enable
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/bluetooth/main.conf
    regexp: 'AutoEnable='
    line: AutoEnable=true

##############################
### timers
##############################
- name: pacman-bar service file
  file:
    src: "{{ role_path }}/files/pacman-bar.service"
    dest: "/home/{{user}}/.config/systemd/user/pacman-bar.service"
    state: link
    owner: "{{ user }}"
    group: "{{ user }}"

- name: pacman-bar service timer
  file:
    src: "{{ role_path }}/files/pacman-bar.timer"
    dest: "/home/{{user}}/.config/systemd/user/pacman-bar.timer"
    state: link
    owner: "{{ user }}"
    group: "{{ user }}"

- name: pacman-bar service
  become: yes
  become_user: "{{ user }}"
  systemd:
    scope: user
    name: pacman-bar.service
    daemon_reload: yes
    state: stopped
    enabled: no

- name: pacman-bar service
  become: yes
  become_user: "{{ user }}"
  systemd:
    scope: user
    name: pacman-bar.service
    daemon_reload: yes

- name: pacman-bar timer
  become: yes
  become_user: "{{ user }}"
  systemd:
    scope: user
    name: pacman-bar.timer
    enabled: no
    state: stopped
    daemon_reload: yes
