---
- name: Pkgs
  become: yes
  pacman:
    name:
      - xorg-server
      - xorg-xclock
      - xorg-xev
      - xorg-xinit
      - xorg-xinput
      - xprintidle
      - xss-lock
      - xterm
      - xclip
      - i3-wm
      - i3lock
      - i3status
      - pulseaudio
      - pulseaudio-alsa
      - pulseaudio-bluetooth
      - pulseaudio-equalizer
      - pavucontrol
      - alacritty
      - arandr
      - dhclient
      - wireless_tools
      - networkmanager
      - network-manager-applet
      - networkmanager-openvpn
      - networkmanager-vpnc
      - ttf-dejavu
      - noto-fonts-cjk
      - noto-fonts-emoji
      - nitrogen
      - libmicrodns
      - vlc
      - thunar
      - chromium
      - dunst
      - tlp
    state: present

- name: conf dirs
  file:
    state: directory
    dest: "{{ user_home }}/.config/{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - dunst
    - fontconfig
    - i3
    - i3status

- name: i3 conf
  file:
    state: link
    src: "{{ role_path }}/files/i3config"
    dest: "{{ user_home }}/.config/i3/config"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: i3 status conf
  file:
    state: link
    src: "{{ role_path }}/files/i3status"
    dest: "{{ user_home }}/.config/i3status/config"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: font config
  file:
    state: link
    src: "{{ role_path }}/files/fonts.conf"
    dest: "{{ user_home }}/.config/fontconfig/fonts.conf"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: dunst config
  file:
    state: link
    src: "{{ role_path }}/files/dunstrc"
    dest: "{{ user_home }}/.config/dunst/dunstrc"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: git prompt
  get_url:
    url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh
    dest: "{{ user_home }}/.git-prompt.sh"
    mode: "0755"

- name: PS1
  blockinfile:
    path: "{{ user_home }}/.bashrc"
    marker: '# PS1: ansible managed block'
    block: |
      [[ -f ~/.git-prompt.sh ]] && source ~/.git-prompt.sh
      export GIT_PS1_SHOWDIRTYSTATE=1
      export GIT_PS1_SHOWUNTRACKEDFILES=1
      PS1='[\u@\h \W]$(__git_ps1 " (%s)")\n\$ '
