---
- name: Pkgs
  become: yes
  pacman:
    name:
      - i3-wm
      - sx
      - xorg-xev
      - xorg-xinit
      - xorg-xinput
      - xprintidle
      - xss-lock
      - xclip
      - i3lock
      - i3status
      - i3blocks
      - sxiv
      - bluez
      - bluez-utils
      - pipewire
      - pipewire-pulse
      - pipewire-alsa
      - pavucontrol
      - pasystray
      - alacritty
      - kitty
      - ueberzug
      - viu
      - arandr
      - dhclient
      - wireless_tools
      - networkmanager
      - network-manager-applet
      - networkmanager-openvpn
      - networkmanager-vpnc
      - ttf-dejavu
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - ttf-jetbrains-mono
      - ttf-nerd-fonts-symbols-1000-em
      - nitrogen
      - libmicrodns
      - vlc
      - thunar
      - gvfs
      - gvfs-smb
      - sshfs
      - chromium
      - dunst
      - tlp
      - z
      - blueman
      - lxappearance
      - arc-gtk-theme
      - papirus-icon-theme
      - docker
      - keychain
      - android-udev
      - archlinux-wallpaper
      - redshift
      - flameshot
      - ntfs-3g
      - udiskie
      - udisks2
      - discord
      - transmission-gtk
      - code
      - linux-headers
      - linux-lts-headers
      - virtualbox
      - virtualbox-host-dkms
      - gimp
      - rofi
      - rofimoji
      - xdotool
      - ttf-roboto
      - ttf-roboto-mono
      - mpv
      - hexchat
      - syncthing
      - keepassxc
      - ristretto
      - w3m
    state: present

- name: Pkgs absent
  become: yes
  pacman:
    name:
      # wezterm and starship don't play well together, just don't install
      - wezterm
    state: absent

- name: emptty dir dirs
  become: yes
  file:
    state: directory
    dest: "/etc/emptty"

- name: emptty conf
  become: yes
  file:
    state: link
    force: yes
    src: "{{ role_path }}/files/empttyconf"
    dest: "/etc/emptty/conf"

- name: xresources
  file:
    state: link
    force: yes
    src: "{{ role_path }}/files/{{ xresources_file }}"
    dest: "{{ user_home}}/.Xresources"
    owner: "{{ user }}"
    group: "{{ user }}"

##############################
### Services
##############################
- name: docker
  become: yes
  systemd:
    name: docker
    enabled: yes
    state: started

- name: docker sytemd
  become: yes
  systemd:
    name: docker
    enabled: yes
    state: started



##############################
### pipewire pulse
##############################

- name: check pipewire patch exists
  stat:
    path: /etc/pipewire/pipewire-pulse.conf.patch
  register: pipewire_patch_path

- name: cleanup old pipewire patch
  become: yes
  when: pipewire_patch_path.stat.exists == True
  ansible.builtin.file:
    path: /etc/pipewire/pipewire-pulse.conf.patch
    state: absent

- name: cleanup old pipewire patch
  become: yes
  when: pipewire_patch_path.stat.exists == True
  ansible.builtin.file:
    path: /etc/pipewire/pipewire-pulse.conf
    state: absent

- name: pipewire custom configs
  become: yes
  copy:
    src: "{{ role_path }}/files/50-pulse-autoswitch.conf"
    dest: /etc/pipewire/pipewire-pulse.conf.d/50-pulse-autoswitch.conf

##############################
### syncthing
##############################
- name: syncthing service
  become: yes
  systemd:
    name: "syncthing@{{ user }}.service"
    daemon_reload: no
    state: started
    enabled: yes

##############################
### bluetooth
##############################
- name: bluetooth
  become: yes
  systemd:
    name: bluetooth
    enabled: yes
    state: started

##############################
### timers
##############################
- name: pacman-bar service file
  file:
    src: "{{ role_path }}/files/pacman-bar.service"
    dest: "/home/{{user}}/.config/systemd/user/pacman-bar.service"
    state: link
    owner: "{{ user }}"
    group: "{{ user }}"

- name: pacman-bar service timer
  file:
    src: "{{ role_path }}/files/pacman-bar.timer"
    dest: "/home/{{user}}/.config/systemd/user/pacman-bar.timer"
    state: link
    owner: "{{ user }}"
    group: "{{ user }}"

- name: pacman-bar service
  become: yes
  become_user: "{{ user }}"
  systemd:
    scope: user
    name: pacman-bar.service
    daemon_reload: yes
    state: stopped
    enabled: no

- name: pacman-bar service
  become: yes
  become_user: "{{ user }}"
  systemd:
    scope: user
    name: pacman-bar.service
    daemon_reload: yes

- name: pacman-bar timer
  become: yes
  become_user: "{{ user }}"
  systemd:
    scope: user
    name: pacman-bar.timer
    enabled: no
    state: stopped
    daemon_reload: yes
