---
- name: install docker
  become: yes
  pacman:
    name:
      - docker
      - docker-compose

- name: enable docker service
  become: yes
  systemd:
    name: docker
    enabled: yes
    state: started
