---
- import_tasks: pacman-base.yml

- import_tasks: timesync.yml

- import_tasks: docker.yml
  when: "arch_common_docker|bool"

- import_tasks: user-groups.yml

# TODO
# figure out a way to manage mkinitcpio hooks
#- import_tasks: swap-hibernate.yml
