---

- name: debug
  tags: debug
  debug:
    msg:
      - Var dump
      - " - user {{ user }}"
      - " - user home {{ user_home }}"
      - " - arch_common_swap_hibernate {{ arch_common_swap_hibernate | bool }}"
      - " - arch_common_sleep_powerbtn {{ arch_common_sleep_powerbtn | bool }}"
      - " - arch_common_docker {{ arch_common_docker | bool }}"
      - " - mkinitcpio_hooks_list {{ mkinitcpio_hooks_list }}"

- import_tasks: pacman-base.yml

- import_tasks: arch-install-guide.yml

- import_tasks: timesync.yml

- import_tasks: docker.yml
  when: "arch_common_docker|bool"

- import_tasks: user-groups.yml

- import_tasks: swap-hibernate.yml
  when: "arch_common_swap_hibernate|bool"

- import_tasks: sleep-powerbtn.yml
  when: "arch_common_sleep_powerbtn|bool"

- import_tasks: nvidia.yml
  when: "arch_common_nvidia|bool"

- import_tasks: mkinitcpio.yml

- import_tasks: root-config.yml
