---
- name: mkinitcpio hooks
  become: true
  lineinfile:
    path: /etc/mkinitcpio.conf
    backup: true
    state: present
    regexp: '^HOOKS='
    line: "HOOKS=({{ mkinitcpio_hooks_lists[mkinitcpio_hooks_list] | join(' ') }})"
  notify:
    - regen-mkinitcpio

- name: mkinitcpio modules
  become: true
  lineinfile:
    path: /etc/mkinitcpio.conf
    backup: true
    state: present
    regexp: '^MODULES='
    line: "MODULES=(vfat)"
  notify:
    - regen-mkinitcpio

- name: kernel modules cleanup from kernel-modules-hook
  become: true
  systemd:
    name: linux-modules-cleanup
    enabled: true
