---
- name: Install pkgs needed on every arch, no gfx
  become: yes
  pacman:
    name:
      - base-devel
      - ansible
      - zip
      - unzip
      - vi
      - vim
      - neovim
      - wget
      - curl
      - whois
      - sudo
      - ruby
      - ruby-irb
      - crystal
      - shards
      - rsync
      - openssh
      - make
      - jq
      - htop
      - fzf
      - bash-completion
      - bc
      - screen
      - tmux
      - git
      - bind
      - the_silver_searcher
      - strace
      - tree
      - pacman-contrib
      - inetutils
      - lsb-release
      - man-db
      - man-pages
      - lsd
      - zsh
      - keychain
      - arch-wiki-docs
      - python-pip
      - python-pipenv
      - rclone
      - fuse2
    state: present

- name: Install on non arm
  become: yes
  when: "'arm' not in ansible_architecture"
  pacman:
    name:
      - reflector
    state: present
