---
- name: Install pkgs needed on every arch, no gfx
  become: yes
  pacman:
    name:
      - base-devel
      - ansible
      - zip
      - unzip
      - vi
      - vim
      - neovim
      - wget
      - curl
      - whois
      - sudo
      - ruby
      - ruby-irb
      - rsync
      - openssh
      - make
      - jq
      - htop
      - fzf
      - bash-completion
      - bc
      - screen
      - tmux
      - git
      - bind
      - the_silver_searcher
      - strace
      - tree
      - pacman-contrib
      - inetutils
    state: present

- name: Install only if not arm
  become: yes
  when: "'arm' not in ansible_facts['ansible_architecture']"
  pacman:
    name:
      - reflector
    state: present
