---
- name: add group
  become: yes
  group:
    name: "{{ user }}"

- name: add user
  become: yes
  user:
    name: "{{ user }}"
    groups: "{{ user }}"
    append: yes

- name: add sudo group
  become: yes
  group:
    name: sudo

- name: add to sudo
  become: yes
  user:
    name: "{{ user }}"
    append: true
    groups: sudo

- name: add to realtime
  become: yes
  user:
    name: "{{ user }}"
    append: true
    groups: realtime

- name: add to docker
  become: yes
  when: "arch_common_docker|bool"
  user:
    name: "{{ user }}"
    append: true
    groups: docker

- name: lockout relax
  become: yes
  blockinfile:
    path: /etc/security/faillock.conf
    marker: '# {mark} ansible maintained settings'
    content: |
      deny = 10

- name: sudo grp config
  become: yes
  lineinfile:
    create: yes
    mode: '0440'
    dest: /etc/sudoers.d/sudo_group
    owner: root
    group: root
    line: '%sudo   ALL=(ALL) ALL'

- name: sudo timeout config
  become: yes
  lineinfile:
    create: yes
    mode: '0440'
    dest: /etc/sudoers.d/sudo_timeout
    owner: root
    group: root
    line: 'Defaults timestamp_timeout=10'

- name: systemd user config units
  file:
    state: directory
    dest: "{{ user_home }}/.config/systemd/user"
    recurse: yes
    owner: "{{ user }}"
    group: "{{ user }}"
