- name: regen-grub
  become: yes
  command: grub-mkconfig -o /boot/grub/grub.cfg

- name: regen-systemdboot
  become: yes
  command: bootctl update

- name: regen-mkinitcpio
  become: yes
  command: mkinitcpio -P

- name: regen-hwclock
  become: yes
  command: hwclock --systohc
  ignore_errors: yes

- name: regen-locale
  become: yes
  command: locale-gen
